name: miktau
root: .
startup_window: lein
windows:
  - testing:
      lein doo phantom
  - lein:
      layout: main-vertical
      panes:
        - electron:
            - cd electron/
            - electron . --disable-http-cache
        - backend:
            - cd /go/src/backend
            - ./backend
        - shell:
            - /etc/init.d/nginx start
            - ls
        - repl:
            - lein repl
            - (go)
